### ISSUE TITLE
Wifi widget always shows disconnected

### ISSUE THREAD

**Issue by hrqmonteiro** [WillPower3309/awesome-dotfiles#20] opened 2020-08-29 20:24 UTC
![2020 08 29-17 24 05 screenshot](https://user-images.githubusercontent.com/17055027/91645564-75873300-ea1c-11ea-82c1-0b9d26dd254a.png)

It shows disconnected even though i AM connected and using wi-fi normally.

**Comment by WillPower3309** [comment] 2020-08-29 22:35
Thanks for the report! Will investigate - I think I have an idea as to what the issue is

**Comment by hrqmonteiro** [comment] 2020-08-29 22:42
Thanks, man! I appreciate.

**Comment by RivierGrullon** [comment] 2020-09-18 18:07
The solution is not implemented yet? I have the same issue u.u

**Comment by WillPower3309** [comment] 2020-09-22 15:52
Apologies, a new theme and school pushed this to the back of my head, will take time to publish a fix tonight.

**Comment by WillPower3309** [comment] 2020-09-25 04:17
@hrqmonteiro @RivierGrullon Appreciate the patience, can you two confirm that you have specified the correct interface in line 22? It defaults to `wlp1s0`. Also, please confirm that you can run `iw` (the command that the config uses to read wifi status)

**Comment by WillPower3309** [comment] 2020-09-25 04:17
On some systems (arch / gentoo) you may need to install it (I neglected to add it to the list of dependencies, which will be fixed)

**Comment by RivierGrullon** [comment] 2020-09-25 18:34
> @hrqmonteiro @RivierGrullon Appreciate the patience, can you two confirm that you have specified the correct interface in line 22? It defaults to `wlp1s0`. Also, please confirm that you can run `iw` (the command that the config uses to read wifi status)

Yup I can run iw, I changed the interface to wlo1 and still have the bug(Honestly I don't know why), hmmmm for now I deactive the wifi widget instead Im using network manager 

psdt: I'm new in Arch

**Comment by WillPower3309** [comment] 2020-09-27 22:01
FIxed :)
Im using the wifi widget from manillarome for the time being until I can implement a better one myself

**Closed by WillPower3309** 2020-09-27 22:01 UTC
Labels: bug
